### PR TITLE
add the sound effect

### PR DESCRIPTION
**Pull request by tcm390**
add the sound effect for pistol. This is the result:

https://user-images.githubusercontent.com/60634884/161134877-6d1e9819-3166-4333-b4e3-23d351a82343.mp4

### CODE REVIEW

**Comment by alisaad673** [comment]
The sfx sounds good but there is an issue with sound:
-The pistol produces shoot sound only when there is an object in front of the aiming point
-While we aim towards the sky or any other place where there's no object, The pistol doesn't produces any sound.

Pistol should produce the sound irrespective of the fact that there is an object in front of aim or not. Though we can add separate sound for when the bullet strikes an object.

https://user-images.githubusercontent.com/35926530/161295147-36940c8a-c6e4-4bee-9cf8-d96a170a5481.mp4

**Comment by tcm390** [comment]
fixed. Could you review again?

**Comment by tcm390** [comment]
https://user-images.githubusercontent.com/60634884/161297151-8fcc196f-1570-4e2a-82f1-9c610515630a.mp4

**Comment by alisaad673** [comment]
Working fine now.

**Review by 0reo — COMMENTED** [review]
this looks good to me

**Pull request merged**
